bamlab/generator-rn-toolbox

README.md, generators/base/README.md, generators/eslint/README.md, generators/fastlane/README.md, generators/jest/README.md
Suggestion to split the README
See https://github.com/bamlab/generator-rn-toolbox/tree/split-readme
@yleflour @tcheymol what do you guys think?
=> Split README for each generator

.eslintrc, package.json
Suggestion to add a linter for the development
=> Add eslint for generator development

.eslintrc, generators/assets/index.js
Writing functions were not returning promises
=> [Assets] Handle conflicts after asset generation

generators/bitrise/templates/bitrise.yml
Do not reinstall Android SDK if already installed
Cache local app gradle cache
=> [Bitrise] Speedup android builds

.eslintrc, generators/fastlane/README.md, generators/fastlane/index.js, generators/fastlane/templates/Gemfile, generators/fastlane/templates/environment/index.js, generators/fastlane/templates/environment/index.prod.js, generators/fastlane/templates/environment/index.staging.js, generators/fastlane/templates/fastlane/.env.prod, generators/fastlane/templates/fastlane/.env.staging, generators/fastlane/templates/fastlane/Fastfile
- Added JS Env
- Fixed Restore bug
- Fixed post setup `bundle install`
- Removed `gym_export_type`
- Added custom Company Name for the keystore
- Updated Fastlane bundle version
- Automatized ios setup 😄
=> [Fastlane] Add JS Env

generators/eslint/templates/eslintignore
It was causing an error on circle-ci since it was also linting files in vendors folder
=> Update Eslint NPM Package Script

generators/fastlane-setup/templates/fastlane/Fastfile
See http://stackoverflow.com/a/3465924/4015394 for difference between display name and name
=> [Fastlane] Update IOS display name from Fastfile

generators/bitrise/README.md, generators/bitrise/index.js, generators/bitrise/templates/bitrise.yml, test.js
This will deploy to TestFlight, and optionally Android Beta, on every push to the `master` branch. We could also do it, so that it deploys on every tag `v{something}` (v1.2, v1.1-rc1...)
=> [Bitrise] Add pre-production workflow (TestFlight + Android Beta)

generators/base/templates/src/components/index.js
Very hazardous missing flow, all components are unwatched
=> fix: Add flow on components

generators/fastlane-env/index.js, generators/fastlane-env/templates/fastlane/env
…/Android
Android and iOS MobileCenter appnames have to be different or otherwise deployment can't make the
difference.
=> (Fix) Fastlane-env: Ask for different app names for iOS/Android if Mobile Center is used for deployment

generators/assets/imageGenerator.js, generators/assets/templates/ios/LaunchImageLaunchimageContents.json
This pull request adds support for the iPhone X splashScreen.
=> feat: add iPhone X SplashScreen support

generators/fastlane-env/README.md, generators/fastlane-env/index.js, generators/fastlane-env/templates/fastlane/env, generators/fastlane-env/templates/fastlane/env.secret, generators/fastlane-setup/templates/fastlane/Fastfile
Microsft has renamed its Mobile Center product to App Center for launch. This commit is to reflect
that change on the generator.
=> refactor($fastlane-env): Rename Mobile Center to App Center

generators/fastlane-env/index.js
=> fix(fastlane-env): Improve step understandability

generators/assets/index.js
=> Fix(assets): Splash creation in Android

.vscode/settings.json, generators/base/index.js, generators/base/templates/src/RootNavigation.js, generators/base/templates/src/modules/App/index.js, generators/base/templates/src/modules/App/module.js, generators/base/templates/src/modules/Nav/index.js, generators/base/templates/src/modules/Nav/module.js, generators/base/templates/src/modules/rootEnhancer.js, generators/base/templates/src/modules/rootReducer.js, generators/base/templates/src/modules/store.js
https://github.com/react-navigation/react-navigation/issues/3475 describe why 1.0 is a breaking
change when using redux intregration.
=> feat(base): update base for react navigation 1.0

generators/advanced-base/templates/src/Scenes.js, generators/advanced-base/templates/src/pages/Account.js, generators/advanced-base/templates/src/pages/Login.js, generators/advanced-base/templates/src/pages/Signup.js, generators/base/templates/src/RootNavigation.js
=> fix(base_advanced-base): Adapt to react-navigation v2

package.json, yarn.lock
=> chore(publish): fix auto publish

generators/base/index.js
=> feat(pencil): remove old App.js when generating base project

generators/advanced-base/index.js
=> feat(pencil): remove old App.js when generating advanced project

generators/fastlane-env/index.js, generators/fastlane-env/templates/fastlane/env, generators/fastlane-setup/templates/fastlane/Fastfile, package.json, yarn.lock
=> fix(fastlane-appcenter): Separate appName from project id

generators/fastlane-setup/templates/fastlane/Fastfile
add update_app_identifier step in ios build phase
conventions
=> fix(fastlane-setup): update fastfile ios build

generators/fastlane-setup/templates/fastlane/Fastfile, generators/fastlane-setup/templates/fastlane/ios_devices.txt, yarn.lock
=> feat(fastlane-setup): Add lane to add ad hoc iOS devices in one command.

.vscode/launch.json, generators/fastlane-env/index.js, generators/fastlane-env/templates/fastlane/env, generators/fastlane-env/templates/fastlane/env.secret, generators/fastlane-setup/templates/fastlane/Fastfile
=> feat(fastlane-env): Add Appcenter SDK and CodePush to fastlane-env

generators/fastlane-setup/templates/fastlane/Fastfile
=> fix(fastlane-setup): Fix backup file breaking Android build.

generators/fastlane-env/index.js, generators/fastlane-env/templates/fastlane/env, generators/fastlane-setup/templates/fastlane/Fastfile
=> feat(fastlane-env): Add production deployments

generators/circleci/README.md, generators/circleci/index.js, generators/circleci/templates/config.yml, generators/fastlane-env/index.js, generators/fastlane-env/templates/fastlane/env, generators/fastlane-setup/index.js, generators/fastlane-setup/templates/deploy.sh, generators/fastlane-setup/templates/fastlane/Fastfile, generators/fastlane-setup/templates/gitignore, package.json
Get a state-of-the art CircleCI deployment script for RN provided you ran fastlane-setup and
fastlane-env answering yes to the deployment + secret handling scripts
conventions
=> feat(circleci): Add CircleCi generator handling all environments

generators/circleci/templates/config.yml, generators/fastlane-env/index.js
- Clarify some questions in fastlane-env
- Fix in CircleCi generator (handle RN being in subfolder)
conventions
=> fix(fastlane): Small fixes in CircleCI and fastlane generators

generators/circleci/index.js, generators/fastlane-env/index.js, generators/fastlane-env/templates/fastlane/env, generators/fastlane-env/templates/fastlane/env.secret, generators/fastlane-setup/templates/fastlane/Fastfile, generators/fastlane-setup/templates/gitignore
=> fix(fastlane-env): Fixes to .env generation for production deployments

generators/fastlane-setup/templates/fastlane/Fastfile
Useful to run app on device
conventions
=> feat(fastlane-setup): Add lane to get all certs and profiles readonly

generators/circleci/templates/config.yml
=> fix(circleci): Fix relative directory
